name: Deploy VitePress to Aliyun OSS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: sso
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: 安装依赖 & 打包 VitePress
        run: |
          npm install
          npm run docs:build
      # 安装阿里云 ossutil
      - name: 安装 ossutil
        run: |
          wget https://gosspublic.alicdn.com/ossutil/1.7.16/ossutil64
          chmod +x ossutil64
          ./ossutil64 config \
            -i ${{ secrets.ALIYUN_ACCESS_KEY_ID }} \
            -k ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }} \
            -e ${{ secrets.ALIYUN_OSS_REGION }}.aliyuncs.com
      # 同步 VitePress 打包产物到 OSS 根目录
      - name: 同步文件到阿里云 OSS
        run: |
          # 本地dist目录 同步到 OSS 根目录
          ./ossutil64 sync .townwang/.vitepress/dist/ oss://${{ secrets.ALIYUN_OSS_BUCKET }}/ \
            --delete --force